export const CENTER_MAP = 'CENTER_MAP';
export const ADD_STOP = 'ADD_STOP';
export const REMOVE_STOP = 'REMOVE_STOP';
export const SET_ACTIVE_STOP = 'SET_ACTIVE_STOP';
export const SET_HIGHLIGHTED_STOP = 'SET_HIGHLIGHTED_STOP';
export const TOGGLE_ADVANCED_SEARCH = 'TOGGLE_ADVANCED_SEARCH';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';

export const FETCH_STOPS_START = 'FETCH_STOPS_START';
export const FETCH_STOPS_SUCCESS = 'FETCH_STOPS_SUCCESS';
export const FETCH_STOPS_ERROR = 'FETCH_STOPS_ERROR';

export const CREATE_STOP_START = 'CREATE_STOP_START';
export const CREATE_STOP_SUCCESS = 'CREATE_STOP_SUCCESS';
export const CREATE_STOP_ERROR = 'CREATE_STOP_ERROR';

export const UPDATE_STOP_START = 'UPDATE_STOP_START';
export const UPDATE_STOP_SUCCESS = 'UPDATE_STOP_SUCCESS';
export const UPDATE_STOP_ERROR = 'UPDATE_STOP_ERROR';

export const DELETE_STOP_START = 'DELETE_STOP_START';
export const DELETE_STOP_SUCCESS = 'DELETE_STOP_SUCCESS';
export const DELETE_STOP_ERROR = 'DELETE_STOP_ERROR';
